In [225]:
!pip install pandas

import pandas as pd
# Taking Access of the raw data.
df = pd.read_csv('customer_shopping_behavior.csv')

Requirement already satisfied: pandas in C:\Users\prade\anaconda3\envs\parthenv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\prade\anaconda3\envs\parthenv\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\prade\anaconda3\envs\parthenv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\prade\anaconda3\envs\parthenv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\prade\anaconda3\envs\parthenv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [226]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [227]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [228]:
df.describe(include = 'all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [229]:
# Checking NaN values in Clounms, and doing there sum with sum() method.
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [230]:
# we are replacing the NaN values with the median, and we take the median category wise for better Results.
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [231]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [232]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [233]:
# Now let's convert the Columns names into lower case or we can sayt in "Snake Case". 

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

# Rename a particular column
df = df.rename(columns = {'purchase_amount_(usd)':'purchase_amount'})

In [234]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [235]:
# create a column age_group

labels = ('Young-Adults','Adult','Middle-Aged','Senior')
df['age_group'] = pd.qcut(df['age'], q = 4 , labels = labels)

In [236]:
df[['age','age_group']].head(50)

    age     age_group
0    55   Middle-Aged
1    19  Young-Adults
2    50   Middle-Aged
3    21  Young-Adults
4    45   Middle-Aged
5    46   Middle-Aged
6    63        Senior
7    27  Young-Adults
8    26  Young-Adults
9    57   Middle-Aged
10   53   Middle-Aged
11   30  Young-Adults
12   61        Senior
13   65        Senior
14   64        Senior
15   64        Senior
16   25  Young-Adults
17   53   Middle-Aged
18   52   Middle-Aged
19   66        Senior
20   21  Young-Adults
21   31  Young-Adults
22   56   Middle-Aged
23   31  Young-Adults
24   18  Young-Adults
25   18  Young-Adults
26   38         Adult
27   56   Middle-Aged
28   54   Middle-Aged
29   31  Young-Adults
30   57   Middle-Aged
31   33         Adult
32   36         Adult
33   54   Middle-Aged
34   36         Adult
35   54   Middle-Aged
36   35         Adult
37   35         Adult
38   29  Young-Adults
39   70        Senior
40   69        Senior
41   67        Senior
42   20  Young-Adults
43   25  Young-Adults
44   39         Adult
45   50   Middle-Aged
46   57   Middle-Aged
47   55   Middle-Aged
48   42         Adult
49   68        Senior

In [237]:
# Create new columns purchase_frequency_days

frequency_mapping ={
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quarterly' : 90,
    'Annually' : 365,
    'Bi-Weekly' : 14,
    'Every 3 Month' : 90
}
# Converting the text info into the numerical to make it easy to analys=ze and compare with other.
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [238]:
df[['purchase_frequency_days','frequency_of_purchases']].head(50)

    purchase_frequency_days frequency_of_purchases
0                      14.0            Fortnightly
1                      14.0            Fortnightly
2                       7.0                 Weekly
3                       7.0                 Weekly
4                     365.0               Annually
5                       7.0                 Weekly
6                      90.0              Quarterly
7                       7.0                 Weekly
8                     365.0               Annually
9                      90.0              Quarterly
10                     14.0              Bi-Weekly
11                     14.0            Fortnightly
12                     14.0            Fortnightly
13                      7.0                 Weekly
14                      7.0                 Weekly
15                     30.0                Monthly
16                     14.0              Bi-Weekly
17                     90.0              Quarterly
18                      7.0                 Weekly
19                     14.0              Bi-Weekly
20                      NaN         Every 3 Months
21                     90.0              Quarterly
22                    365.0               Annually
23                      7.0                 Weekly
24                      7.0                 Weekly
25                    365.0               Annually
26                    365.0               Annually
27                      NaN         Every 3 Months
28                      NaN         Every 3 Months
29                      7.0                 Weekly
30                     30.0                Monthly
31                     30.0                Monthly
32                    365.0               Annually
33                     90.0              Quarterly
34                     90.0              Quarterly
35                     14.0              Bi-Weekly
36                     14.0            Fortnightly
37                      7.0                 Weekly
38                      NaN         Every 3 Months
39                     30.0                Monthly
40                     90.0              Quarterly
41                    365.0               Annually
42                    365.0               Annually
43                     14.0            Fortnightly
44                      7.0                 Weekly
45                    365.0               Annually
46                     90.0              Quarterly
47                      7.0                 Weekly
48                     30.0                Monthly
49                     14.0              Bi-Weekly

In [239]:
# Now let's Check the discount and promo code columns 
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [240]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [241]:
df = df.drop('promo_code_used', axis = 1 )

In [242]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [243]:
# Overwrite original CSV with cleaned data
df.to_csv("customer_shopping_behavior.csv", index=False)

# Verify
df = pd.read_csv("customer_shopping_behavior.csv")
print(df.head())

   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
4            5   45   Male         Blouse  Clothing               49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14          Venmo
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49         PayPal
4  Free Shipping              Yes                  31         PayPal

  frequency_of_purchases     age_group  purchase_frequency_days
0            Fortnightly   Middle-Aged                     14.0
1            Fortnightly  Young-Adults                     14.0
2                 Weekly   Middle-Aged                      7.0
3                 Weekly  Young-Adults                      7.0
4               Annually   Middle-Aged                    365.0

In [245]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in C:\Users\prade\anaconda3\envs\parthenv\Lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in C:\Users\prade\anaconda3\envs\parthenv\Lib\site-packages (2.0.51)
Requirement already satisfied: greenlet>=1 in C:\Users\prade\anaconda3\envs\parthenv\Lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\prade\anaconda3\envs\parthenv\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [246]:
from sqlalchemy import create_engine


# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"         # default user
password = "Parth9088" # the password you set during installation
host = "localhost"          # if running locally
port = "5432"               # default PostgreSQL port
database = "customer_behavior"   # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"     # choose any table name

In [247]:
import pandas as pd

df = pd.read_csv("customer_shopping_behavior.csv")

df.to_sql(
    table_name,
    engine,
    if_exists="replace",   # replace existing table
    index=False            # don't create index column
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.

In [248]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [249]:
print(df.shape)

(3900, 19)

In [250]:
df.head(50)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-Aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young-Adults,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-Aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young-Adults,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-Aged,365.0
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Middle-Aged,7.0
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior,90.0
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,Young-Adults,7.0
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,Young-Adults,365.0
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle-Aged,90.0
10,11,53,Male,Shoes,Footwear,34,Arkansas,L,Purple,Fall,4.1,Yes,Store Pickup,Yes,26,Bank Transfer,Bi-Weekly,Middle-Aged,14.0
11,12,30,Male,Shorts,Clothing,68,Hawaii,S,Olive,Winter,4.9,Yes,Store Pickup,Yes,10,Bank Transfer,Fortnightly,Young-Adults,14.0
12,13,61,Male,Coat,Outerwear,72,Delaware,M,Gold,Winter,4.5,Yes,Express,Yes,37,Venmo,Fortnightly,Senior,14.0
13,14,65,Male,Dress,Clothing,51,New Hampshire,M,Violet,Spring,4.7,Yes,Express,Yes,31,PayPal,Weekly,Senior,7.0
14,15,64,Male,Coat,Outerwear,53,New York,L,Teal,Winter,4.7,Yes,Free Shipping,Yes,34,Debit Card,Weekly,Senior,7.0
15,16,64,Male,Skirt,Clothing,81,Rhode Island,M,Teal,Winter,2.8,Yes,Store Pickup,Yes,8,PayPal,Monthly,Senior,30.0
16,17,25,Male,Sunglasses,Accessories,36,Alabama,S,Gray,Spring,4.1,Yes,Next Day Air,Yes,44,Debit Card,Bi-Weekly,Young-Adults,14.0
17,18,53,Male,Dress,Clothing,38,Mississippi,XL,Lavender,Winter,4.7,Yes,2-Day Shipping,Yes,36,Venmo,Quarterly,Middle-Aged,90.0
18,19,52,Male,Sweater,Clothing,48,Montana,S,Black,Summer,4.6,Yes,Free Shipping,Yes,17,Cash,Weekly,Middle-Aged,7.0
19,20,66,Male,Pants,Clothing,90,Rhode Island,M,Green,Summer,3.3,Yes,Standard,Yes,46,Debit Card,Bi-Weekly,Senior,14.0
20,21,21,Male,Pants,Clothing,51,Louisiana,M,Black,Winter,2.8,Yes,Express,Yes,50,Cash,Every 3 Months,Young-Adults,NaN
21,22,31,Male,Pants,Clothing,62,North Carolina,M,Charcoal,Winter,4.1,Yes,Store Pickup,Yes,22,Debit Card,Quarterly,Young-Adults,90.0
22,23,56,Male,Pants,Clothing,37,California,M,Peach,Summer,3.2,Yes,Store Pickup,Yes,32,Debit Card,Annually,Middle-Aged,365.0
23,24,31,Male,Pants,Clothing,88,Oklahoma,XL,White,Winter,4.4,Yes,Express,Yes,40,Credit Card,Weekly,Young-Adults,7.0
24,25,18,Male,Jacket,Outerwear,22,Florida,M,Green,Fall,2.9,Yes,Store Pickup,Yes,16,Debit Card,Weekly,Young-Adults,7.0
25,26,18,Male,Hoodie,Clothing,25,Texas,M,Silver,Summer,3.6,Yes,Express,Yes,14,PayPal,Annually,Young-Adults,365.0
26,27,38,Male,Jewelry,Accessories,20,Nevada,M,Red,Spring,3.6,Yes,Next Day Air,Yes,13,Credit Card,Annually,Adult,365.0
27,28,56,Male,Shorts,Clothing,56,Kentucky,L,Cyan,Summer,5.0,Yes,Next Day Air,Yes,7,Bank Transfer,Every 3 Months,Middle-Aged,NaN
28,29,54,Male,Handbag,Accessories,94,North Carolina,M,Gray,Fall,4.4,Yes,Free Shipping,Yes,41,PayPal,Every 3 Months,Middle-Aged,NaN
29,30,31,Male,Dress,Clothing,48,Wyoming,S,Black,Fall,4.1,Yes,Store Pickup,Yes,14,Credit Card,Weekly,Young-Adults,7.0
30,31,57,Male,Jewelry,Accessories,31,North Carolina,L,Black,Winter,4.7,Yes,Standard,Yes,16,Credit Card,Monthly,Middle-Aged,30.0
31,32,33,Male,Dress,Clothing,79,West Virginia,L,Brown,Winter,4.7,Yes,Store Pickup,Yes,45,Venmo,Monthly,Adult,30.0
32,33,36,Male,Jacket,Outerwear,67,Kansas,M,Silver,Summer,4.9,Yes,Free Shipping,Yes,37,Venmo,Annually,Adult,365.0
33,34,54,Male,Pants,Clothing,38,Colorado,L,Green,Summer,3.3,Yes,Store Pickup,Yes,45,Cash,Quarterly,Middle-Aged,90.0
34,35,36,Male,T-shirt,Clothing,91,North Dakota,L,Violet,Spring,4.6,Yes,2-Day Shipping,Yes,38,PayPal,Quarterly,Adult,90.0
35,36,54,Male,Blouse,Clothing,33,Massachusetts,M,Cyan,Summer,4.0,Yes,2-Day Shipping,Yes,48,Credit Card,Bi-Weekly,Middle-Aged,14.0
36,37,35,Male,T-shirt,Clothing,69,Illinois,M,Maroon,Winter,4.6,Yes,Free Shipping,Yes,44,PayPal,Fortnightly,Adult,14.0
37,38,35,Male,Jeans,Clothing,45,Indiana,S,Cyan,Summer,2.8,Yes,Store Pickup,Yes,10,PayPal,Weekly,Adult,7.0
38,39,29,Male,Dress,Clothing,37,Florida,M,Red,Winter,3.7,Yes,2-Day Shipping,Yes,44,Venmo,Every 3 Months,Young-Adults,NaN
39,40,70,Male,Pants,Clothing,60,Arizona,S,Turquoise,Summer,4.2,Yes,Express,Yes,18,Credit Card,Monthly,Senior,30.0
40,41,69,Male,Handbag,Accessories,76,Louisiana,L,Beige,Winter,4.6,Yes,Next Day Air,Yes,31,Debit Card,Quarterly,Senior,90.0
41,42,67,Male,Scarf,Accessories,39,Alaska,M,Orange,Spring,4.5,Yes,Standard,Yes,40,Venmo,Annually,Senior,365.0
42,43,20,Male,Coat,Outerwear,100,Tennessee,M,Beige,Spring,4.1,Yes,Free Shipping,Yes,15,PayPal,Annually,Young-Adults,365.0
43,44,25,Male,Scarf,Accessories,69,Ohio,L,Lavender,Fall,3.7,Yes,Store Pickup,Yes,19,PayPal,Fortnightly,Young-Adults,14.0
44,45,39,Male,Hat,Accessories,53,Kentucky,S,Silver,Summer,4.6,Yes,Free Shipping,Yes,45,PayPal,Weekly,Adult,7.0
45,46,50,Male,Socks,Clothing,21,Tennessee,XL,Indigo,Fall,2.9,Yes,2-Day Shipping,Yes,25,PayPal,Annually,Middle-Aged,365.0
46,47,57,Male,Shirt,Clothing,43,California,L,White,Summer,2.9,Yes,Store Pickup,Yes,45,Cash,Quarterly,Middle-Aged,90.0
47,48,55,Male,Jewelry,Accessories,54,Montana,M,Charcoal,Winter,4.5,Yes,Free Shipping,Yes,36,Cash,Weekly,Middle-Aged,7.0
48,49,42,Male,Shirt,Clothing,55,Nevada,M,Orange,Summer,2.7,Yes,Store Pickup,Yes,38,Cash,Monthly,Adult,30.0
49,50,68,Male,Hoodie,Clothing,30,New Jersey,S,Indigo,Spring,4.6,Yes,Next Day Air,Yes,34,Debit Card,Bi-Weekly,Senior,14.0